import { NextResponse } from "next/server";
import { OrdersStore } from "@/lib/services/ordersStore";
import { NotificationsStore } from "@/lib/services/notificationsStore";
import { N8nAutomationService } from "@/lib/services/n8nService";

export async function POST(req: Request) {
  try {
    // 1. Verify shared webhook secret
    const isAuthorized = N8nAutomationService.verifySecretHeader(req);
    if (!isAuthorized && process.env.NODE_ENV === "production") {
      return NextResponse.json(
        { error: "Unauthorized: Invalid or missing x-sutra-secret header." },
        { status: 401 }
      );
    }

    const payload = await req.json();
    const {
      orderId,
      clientId,
      runId,
      workflowId,
      status, // "draft_ready" | "completed" | "generation_failed" | "published" | "task_created"
      deliverables,
      deliverableUrl,
      filename,
      driveFolder,
      taskSummary,
      error,
      retryCount,
      notes,
    } = payload;

    const now = new Date().toISOString();
    console.log(
      `[Sutra n8n Webhook] Workflow: ${workflowId}, Run: ${runId}, Status: ${status}, Order: ${orderId}`
    );

    if (orderId) {
      const order = OrdersStore.findById(orderId);
      if (order) {
        // Track workflow history
        if (!order.workflowHistory) order.workflowHistory = [];
        order.workflowHistory.push({
          runId: runId || `run_${Date.now()}`,
          workflowId: workflowId || "W1_order_fulfillment_router",
          status: status || "completed",
          timestamp: now,
          deliverableUrl: deliverableUrl || (deliverables && deliverables[0]?.previewUrl),
          error: error || undefined,
        });

        order.workflowStatus = status === "generation_failed" ? "generation_failed" : "draft_ready";
        order.workflowRunId = runId;
        if (error) order.workflowLastError = error;

        // Case A: AI Draft Ready -> Save to Drive '02 Drafts' & Notify Admin (NOT client)
        if (status === "draft_ready" || status === "completed") {
          const newDeliverables = Array.isArray(deliverables) && deliverables.length > 0
            ? deliverables
            : deliverableUrl || filename
            ? [
                {
                  driveFileId: `drive_n8n_${runId || Date.now()}`,
                  filename: filename || `${order.service || "Creative"}_Concept_Draft_01.png`,
                  checksum: `sha256:${Math.random().toString(36).substring(2, 14)}`,
                  fileSize: "12.4 MB",
                  mimeType: "image/png",
                  previewUrl: deliverableUrl,
                  category: "draft" as const,
                  version: `v1.${(order.workflowRetryCount || 1)}`,
                  uploadedAt: now,
                },
              ]
            : [];

          if (newDeliverables.length > 0) {
            if (!order.deliverables) order.deliverables = [];
            order.deliverables.push(...newDeliverables);
          }

          order.status = "draft_delivered";
          order.statusLabel = "Draft Vaulted — Awaiting Admin Review";
          order.updatedAt = now;

          if (!order.statusHistory) order.statusHistory = [];
          order.statusHistory.push({
            status: "draft_delivered",
            changedAt: now,
            changedBy: "n8n_automation",
            note: `n8n [${workflowId || "W1"}] placed concept drafts in Drive '02 Drafts'. Awaiting studio admin review before client release.`,
          });

          // STRICT RULE: Notify Admin ONLY, never send unverified AI output to client
          NotificationsStore.add({
            userId: "usr_admin_001",
            type: "order_delivered",
            title: "Draft Ready for Admin Review",
            message: `Order #${order.orderNumber || order.code} has new drafts generated by [${workflowId || "W1"}]. Please inspect before client delivery.`,
            orderId: order.id,
            orderNumber: order.orderNumber || order.code,
            actionUrl: `/admin/orders?id=${order.id}`,
            actionLabel: "Review Draft in Vault",
          });
        }

        // Case B: Human-Production Task Created
        else if (status === "task_created") {
          order.status = "in_production";
          order.statusLabel = "Production Task Queued for Studio Team";
          order.updatedAt = now;

          if (taskSummary) {
            if (!order.internalNotes) order.internalNotes = [];
            order.internalNotes.push({
              id: `note_task_${Date.now()}`,
              authorName: "Sutra n8n Engine",
              text: `Automated Task Brief: ${taskSummary}`,
              createdAt: now,
            });
          }

          NotificationsStore.add({
            userId: "usr_admin_001",
            type: "status_update",
            title: "Human Production Task Queued",
            message: `Brief breakdown & Drive workspace prepared for #${order.orderNumber || order.code} (${order.service}).`,
            orderId: order.id,
            orderNumber: order.orderNumber || order.code,
            actionUrl: `/admin/orders?id=${order.id}`,
            actionLabel: "View Production Task",
          });
        }

        // Case C: Generation Failed -> Mark failure, notify admin with retry link
        else if (status === "generation_failed") {
          order.workflowStatus = "generation_failed";
          order.workflowLastError = error || "Automated draft rendering failed.";
          order.updatedAt = now;

          if (!order.statusHistory) order.statusHistory = [];
          order.statusHistory.push({
            status: "generation_failed",
            changedAt: now,
            changedBy: "n8n_error_handler",
            note: `Pipeline failure in [${workflowId || "W1"}]: ${error || "Unknown error"}. Retry link available in admin console.`,
          });

          NotificationsStore.add({
            userId: "usr_admin_001",
            type: "status_update",
            title: "Pipeline Failure Alert",
            message: `Automation failed on #${order.orderNumber || order.code} [${workflowId || "W1"}]. Reason: ${error || "API rate limit or invalid brief"}. Click to retry or assign manually.`,
            orderId: order.id,
            orderNumber: order.orderNumber || order.code,
            actionUrl: `/admin/orders?id=${order.id}&retry=true`,
            actionLabel: "Retry Pipeline",
          });
        }

        // Case D: Published to Social Media (W2 / W5)
        else if (status === "published") {
          if (!order.statusHistory) order.statusHistory = [];
          order.statusHistory.push({
            status: "completed",
            changedAt: now,
            changedBy: "n8n_meta_publisher",
            note: `Approved creative published to connected Meta account: ${notes || "Instagram/Facebook live"}.`,
          });

          NotificationsStore.add({
            userId: order.clientUid || order.clientId || "usr_client_001",
            type: "status_update",
            title: "Creative Published Live",
            message: `Your approved post for #${order.orderNumber || order.code} is now live on your connected social channels.`,
            orderId: order.id,
            orderNumber: order.orderNumber || order.code,
            actionUrl: `/orders?id=${order.id}`,
            actionLabel: "View Live Post",
          });
        }
      }
    }

    return NextResponse.json({
      received: true,
      workflowId,
      runId,
      status: status || "processed",
      updatedAt: now,
      message: `State verified and synchronized to Sutra Studio master ledger.`,
    });
  } catch (error) {
    return NextResponse.json(
      {
        error: "Invalid webhook payload structure.",
        details: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 400 }
    );
  }
}

export async function GET() {
  return NextResponse.json({
    service: "Sutra Studio n8n Webhook Gateway",
    version: "2.0.0",
    status: "online",
    authRequirement: "x-sutra-secret header",
    activePipelines: [
      { id: "W1_order_fulfillment_router", name: "Order Fulfillment Router" },
      { id: "W2_approval_and_publish", name: "Post-Approval Meta & IG Publisher" },
      { id: "W3_monthly_plan_content", name: "Monthly Retainer Content Generator" },
      { id: "W4_error_handler", name: "Global Execution Error Handler" },
      { id: "W5_agency_daily_autopost", name: "Agency Daily Social Autoposter" },
    ],
  });
}
