/**
 * SUTRA STUDIO — Missing Key Registry Service
 *
 * Implements Step 31A: Centralized missing-key tracking, Firestore registry sync,
 * daily throttled admin alerts, and automatic MISSING_KEYS.md regeneration.
 *
 * HARD RULES:
 *  1. NEVER prints, logs, or stores secret values.
 *  2. NEVER modifies, overwrites, rotates, or deletes existing non-empty env values.
 *  3. Only appends missing names with empty values (`NAME=`) to env files.
 *  4. Throttles notifications & emails to at most once per key/day.
 *  5. Gracefully handles missing keys without throwing unhandled exceptions or generating fake output.
 */

import fs from "fs";
import path from "path";
import { type EnvKey, readEnv, isEnvSet } from "@/lib/config/env";
import {
  INTEGRATION_DEFINITIONS,
  type IntegrationPriority,
  getIntegrationStatuses,
} from "@/lib/config/integrations";
import { NotificationsStore } from "./notificationsStore";
import { EmailService } from "./emailProvider";

const ROOT_DIR = process.cwd();
const ENV_LOCAL_PATH = path.join(ROOT_DIR, ".env.local");
const ENV_EXAMPLE_PATH = path.join(ROOT_DIR, ".env.example");
const MISSING_KEYS_MD_PATH = path.join(ROOT_DIR, "MISSING_KEYS.md");
const BACKUP_DIR = path.join(ROOT_DIR, "scripts", "backups", "env-backups");

export interface MissingKeyRecord {
  key: EnvKey;
  feature: string;
  priority: IntegrationPriority;
  firstNeededAt: string;
  lastNeededAt: string;
  count: number;
  configured: boolean;
  whereToGet: string;
  lastNotifiedAt?: string;
}

/**
 * Ensures backup directory exists and creates local timestamped backup of env files before modification.
 */
export function backupEnvFiles(): void {
  try {
    if (!fs.existsSync(BACKUP_DIR)) {
      fs.mkdirSync(BACKUP_DIR, { recursive: true });
    }
    const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
    if (fs.existsSync(ENV_LOCAL_PATH)) {
      const backupPath = path.join(BACKUP_DIR, `.env.local.${timestamp}.bak`);
      fs.copyFileSync(ENV_LOCAL_PATH, backupPath);
    }
    if (fs.existsSync(ENV_EXAMPLE_PATH)) {
      const backupPath = path.join(BACKUP_DIR, `.env.example.${timestamp}.bak`);
      fs.copyFileSync(ENV_EXAMPLE_PATH, backupPath);
    }
  } catch (err) {
    console.warn("[MissingKeyRegistry] Env backup warning:", err);
  }
}

/**
 * Appends a variable name with empty value to .env.local and .env.example if absent.
 * Never touches or overwrites existing variables.
 */
export function appendMissingEnvKeyIfAbsent(keyName: string): void {
  try {
    backupEnvFiles();

    // Check .env.local
    if (fs.existsSync(ENV_LOCAL_PATH)) {
      const content = fs.readFileSync(ENV_LOCAL_PATH, "utf-8");
      const regex = new RegExp(`^${keyName}=`, "m");
      if (!regex.test(content)) {
        const endingNewline = content.endsWith("\n") ? "" : "\n";
        fs.appendFileSync(ENV_LOCAL_PATH, `${endingNewline}${keyName}=\n`, "utf-8");
      }
    }

    // Check .env.example
    if (fs.existsSync(ENV_EXAMPLE_PATH)) {
      const content = fs.readFileSync(ENV_EXAMPLE_PATH, "utf-8");
      const regex = new RegExp(`^${keyName}=`, "m");
      if (!regex.test(content)) {
        const endingNewline = content.endsWith("\n") ? "" : "\n";
        fs.appendFileSync(ENV_EXAMPLE_PATH, `${endingNewline}${keyName}=\n`, "utf-8");
      }
    }
  } catch (err) {
    console.warn(`[MissingKeyRegistry] Could not append key ${keyName}:`, err);
  }
}

/**
 * Regenerates MISSING_KEYS.md with up-to-date missing keys and instructions.
 * Exposes names and setup instructions ONLY — NEVER values.
 */
export function regenerateMissingKeysMarkdown(): void {
  try {
    const statuses = getIntegrationStatuses();
    const missingItems = statuses.filter((s) => s.state === "not configured");

    const lines: string[] = [
      "# MISSING_KEYS.md — Sutra Studio",
      "",
      "**Names only. Never put a real value in this file.**",
      "",
      "> Automatically generated by the SutraStudio Missing-Key Registry.",
      `> Last synchronized: ${new Date().toISOString()}`,
      "",
      "---",
      "",
      "## Missing Integrations Summary",
      "",
      `Total missing services: **${missingItems.length}** / **${statuses.length}** configured.`,
      "",
      "| # | Integration | Priority | Missing Variables | Impacted Features | Where to Get |",
      "|---|---|---|---|---|---|",
    ];

    let index = 1;
    for (const item of missingItems) {
      const keysStr = item.missingKeys.map((k) => `\`${k}\``).join(", ");
      const featuresStr = item.features.join(", ");
      lines.push(
        `| ${index++} | **${item.name}** | \`${item.priority}\` | ${keysStr} | ${featuresStr} | ${item.whereToGet} |`
      );
    }

    lines.push(
      "",
      "---",
      "",
      "## Configured Integrations (Ready)",
      "",
      "| Integration | Group | Ready Keys |",
      "|---|---|---|",
    );

    const configuredItems = statuses.filter((s) => s.state === "configured");
    for (const item of configuredItems) {
      const keysStr = item.presentKeys.map((k) => `\`${k}\``).join(", ");
      lines.push(`| **${item.name}** | ${item.group} | ${keysStr || "All Set"} |`);
    }

    lines.push(
      "",
      "---",
      "",
      "## Environment Policy Reminders",
      "",
      "- **Zero Fake Outputs**: When an integration is missing, endpoints gracefully return structured 503 notices rather than generating fake or mock production data.",
      "- **Zero Secret Leaks**: Client components never receive server secrets. All keys remain server-side.",
      "- **Automated Alerts**: Studio administrators receive at most one in-app notification and one email per day for unconfigured critical integrations.",
      ""
    );

    fs.writeFileSync(MISSING_KEYS_MD_PATH, lines.join("\n"), "utf-8");
  } catch (err) {
    console.warn("[MissingKeyRegistry] Failed to regenerate MISSING_KEYS.md:", err);
  }
}

/**
 * Record a missing key invocation in Firestore, throttle notifications, and update files.
 */
export async function recordMissingKey(options: {
  key: EnvKey;
  feature: string;
  priority?: IntegrationPriority;
  whereToGet?: string;
}): Promise<void> {
  const { key, feature, priority = "HIGH" } = options;

  // 1. Append empty variable to env files if absent
  appendMissingEnvKeyIfAbsent(key);

  // 2. Lookup where to get instructions
  let whereToGet = options.whereToGet;
  if (!whereToGet) {
    for (const def of INTEGRATION_DEFINITIONS) {
      const req = def.requirements.find((r) => r.key === key);
      if (req) {
        whereToGet = req.whereToGet || def.whereToGet;
        break;
      }
    }
  }
  whereToGet = whereToGet || "Check .env.example or studio documentation.";

  const nowIso = new Date().toISOString();

  // 3. Record in Firestore `integrationStatus/{name}`
  let shouldSendDailyAlert = false;

  try {
    const { adminDb } = await import("@/lib/firebase/admin");
    const docRef = adminDb().collection("integrationStatus").doc(key);
    const snap = await docRef.get();

    if (!snap.exists) {
      await docRef.set({
        key,
        feature,
        features: [feature],
        priority,
        firstNeededAt: nowIso,
        lastNeededAt: nowIso,
        count: 1,
        configured: false,
        whereToGet,
        lastNotifiedAt: nowIso,
      });
      shouldSendDailyAlert = true;
    } else {
      const data = snap.data() || {};
      const count = (data.count || 0) + 1;
      const features: string[] = Array.from(new Set([...(data.features || []), feature]));
      const lastNotified = data.lastNotifiedAt ? new Date(data.lastNotifiedAt).getTime() : 0;
      const hoursSinceNotification = (Date.now() - lastNotified) / (1000 * 60 * 60);

      const updates: Record<string, unknown> = {
        lastNeededAt: nowIso,
        count,
        features,
        configured: false,
        whereToGet,
      };

      if (hoursSinceNotification >= 24) {
        updates.lastNotifiedAt = nowIso;
        shouldSendDailyAlert = true;
      }

      await docRef.update(updates);
    }
  } catch (err) {
    // Firestore might be unavailable in local offline mode
    console.warn(`[MissingKeyRegistry] Firestore sync skipped for ${key}:`, err);
  }

  // 4. Daily Throttled Admin Notification & Email
  if (shouldSendDailyAlert) {
    try {
      NotificationsStore.add({
        userId: "admin",
        type: "status_update",
        title: `Integration Key Required: ${key}`,
        message: `Feature "${feature}" requested variable ${key} (Priority: ${priority}). Add to .env.local to activate.`,
        actionUrl: "/admin/integrations",
        actionLabel: "View Integrations Registry",
        idempotencyKey: `missing_key_${key}_${nowIso.split("T")[0]}`,
        metadata: {
          key,
          priority,
          feature,
          whereToGet,
        },
      });

      const adminNotifyEmail = readEnv("ADMIN_NOTIFY_EMAIL") || readEnv("ADMIN_EMAIL");
      if (adminNotifyEmail) {
        await EmailService.dispatchNotificationEmail({
          to: adminNotifyEmail,
          type: "status_update",
          title: `[Sutra Studio Action Required] Missing Key: ${key}`,
          message: `The studio feature "${feature}" attempted to use ${key} (Priority: ${priority}), but it is currently unconfigured. Credential Source: ${whereToGet}. Please configure this in .env.local.`,
          actionUrl: "/admin/integrations",
          actionLabel: "View Integrations Registry",
        });
      }
    } catch (notifErr) {
      console.warn("[MissingKeyRegistry] Notification dispatch notice:", notifErr);
    }
  }

  // 5. Regenerate MISSING_KEYS.md
  regenerateMissingKeysMarkdown();
}

/**
 * Safe accessor for environment variables that logs and tracks missing keys without crashing.
 */
export function safeGetEnv(
  key: EnvKey,
  context: { feature: string; priority?: IntegrationPriority; fallback?: string }
): string {
  const value = readEnv(key);
  if (!value) {
    // Asynchronously record missing key
    void recordMissingKey({
      key,
      feature: context.feature,
      priority: context.priority,
    });
    return context.fallback ?? "";
  }
  return value;
}

/**
 * Synchronizes all integration definitions into Firestore `integrationStatus/{name}`.
 */
export async function syncAllIntegrationsToFirestore(): Promise<void> {
  const statuses = getIntegrationStatuses();

  try {
    const { adminDb } = await import("@/lib/firebase/admin");

    for (const item of statuses) {
      for (const key of item.missingKeys) {
        try {
          const docRef = adminDb().collection("integrationStatus").doc(key);
          const snap = await docRef.get();
          const nowIso = new Date().toISOString();

          if (!snap.exists) {
            await docRef.set({
              key,
              feature: item.features[0] || item.name,
              features: item.features,
              priority: item.priority,
              firstNeededAt: nowIso,
              lastNeededAt: nowIso,
              count: 1,
              configured: false,
              whereToGet: item.whereToGet,
            });
          }
        } catch (err) {
          console.warn(`[MissingKeyRegistry] Sync skipped for ${key}:`, err);
        }
      }

      for (const key of item.presentKeys) {
        try {
          const docRef = adminDb().collection("integrationStatus").doc(key);
          await docRef.set(
            {
              key,
              features: item.features,
              priority: item.priority,
              configured: true,
              whereToGet: item.whereToGet,
              lastCheckedAt: new Date().toISOString(),
            },
            { merge: true }
          );
        } catch {
          // ignore
        }
      }
    }
  } catch (err) {
    console.warn("[MissingKeyRegistry] Firestore admin unavailable:", err);
  }

  regenerateMissingKeysMarkdown();
}
