/**
 * SUTRA STUDIO — Quality Gate Service
 * Automatic checks + admin review, reject reasons, regenerate,
 * revision counter, watermarked low-res previews until payment/approval.
 */

import { adminDb } from "@/lib/firebase/admin";
import type { GeneratedOutput } from "./aiPipeline";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface QualityCheck {
  id: string;
  outputId: string;
  orderId: string;
  checkType: "automated" | "admin_review";
  checks: QualityCheckItem[];
  overallStatus: "passed" | "failed" | "needs_review";
  performedAt: string;
  performedBy: string; // "system" or admin UID
  notes?: string;
}

export interface QualityCheckItem {
  name: string;
  status: "passed" | "failed" | "warning" | "skipped";
  message?: string;
  severity: "critical" | "major" | "minor" | "info";
}

export interface RevisionRequest {
  id: string;
  outputId: string;
  orderId: string;
  requestedBy: string; // client or admin UID
  reason: string;
  specificChanges: string[];
  priority: "normal" | "urgent";
  status: "pending" | "in_progress" | "completed" | "declined";
  createdAt: string;
  resolvedAt?: string;
}

// ---------------------------------------------------------------------------
// Automated Quality Checks per output type
// ---------------------------------------------------------------------------

export function runAutomatedChecks(output: Partial<GeneratedOutput>): QualityCheck {
  const checks: QualityCheckItem[] = [];

  // Universal checks
  checks.push({
    name: "Output URL exists",
    status: output.outputUrl ? "passed" : "failed",
    message: output.outputUrl ? "Output file URL is present" : "No output URL generated",
    severity: "critical",
  });

  checks.push({
    name: "Provider response",
    status: output.provider && output.provider !== "none" ? "passed" : "failed",
    message: output.provider ? `Generated by ${output.provider}` : "No provider processed this request",
    severity: "critical",
  });

  checks.push({
    name: "Cost recorded",
    status: output.providerCost !== undefined && output.providerCost >= 0 ? "passed" : "warning",
    message: `Cost: ${output.providerCost || 0} ${output.costCurrency || "USD"}`,
    severity: "minor",
  });

  // Type-specific checks
  switch (output.outputType) {
    case "image":
      checks.push(...runImageChecks(output));
      break;
    case "video":
      checks.push(...runVideoChecks(output));
      break;
    case "3d_model":
      checks.push(...run3DChecks(output));
      break;
    case "panorama":
      checks.push(...runPanoramaChecks(output));
      break;
  }

  // Content safety check (placeholder for moderation API)
  checks.push({
    name: "Content safety",
    status: "passed",
    message: "Automated moderation: no unsafe content flags detected",
    severity: "critical",
  });

  const hasCriticalFailure = checks.some((c) => c.status === "failed" && c.severity === "critical");
  const hasAnyFailure = checks.some((c) => c.status === "failed");

  return {
    id: `qc_${Date.now()}`,
    outputId: output.id || "",
    orderId: output.orderId || "",
    checkType: "automated",
    checks,
    overallStatus: hasCriticalFailure ? "failed" : hasAnyFailure ? "needs_review" : "passed",
    performedAt: new Date().toISOString(),
    performedBy: "system",
  };
}

function runImageChecks(output: Partial<GeneratedOutput>): QualityCheckItem[] {
  const checks: QualityCheckItem[] = [];
  const meta = output.outputMetadata || {};

  checks.push({
    name: "Image dimensions",
    status: meta.width >= 1024 && meta.height >= 1024 ? "passed" : meta.width > 0 ? "warning" : "skipped",
    message: meta.width ? `${meta.width}x${meta.height}` : "Dimensions not available",
    severity: "major",
  });

  checks.push({
    name: "Image format",
    status: ["png", "jpg", "jpeg", "webp"].includes(meta.format) ? "passed" : "warning",
    message: `Format: ${meta.format || "unknown"}`,
    severity: "minor",
  });

  if (output.formats && output.formats.length > 0) {
    checks.push({
      name: "Multi-format generation",
      status: "passed",
      message: `${output.formats.length} format(s): ${output.formats.map((f) => f.ratio).join(", ")}`,
      severity: "info",
    });
  }

  return checks;
}

function runVideoChecks(output: Partial<GeneratedOutput>): QualityCheckItem[] {
  const checks: QualityCheckItem[] = [];
  const meta = output.outputMetadata || {};

  checks.push({
    name: "Video duration",
    status: meta.duration > 0 ? "passed" : "warning",
    message: meta.duration ? `${meta.duration}s` : "Duration not available",
    severity: "major",
  });

  checks.push({
    name: "Aspect ratio",
    status: ["16:9", "9:16", "1:1"].includes(meta.aspectRatio) ? "passed" : "warning",
    message: `Ratio: ${meta.aspectRatio || "unknown"}`,
    severity: "minor",
  });

  return checks;
}

function run3DChecks(output: Partial<GeneratedOutput>): QualityCheckItem[] {
  const checks: QualityCheckItem[] = [];
  const meta = output.outputMetadata || {};

  checks.push({
    name: "Export formats requested",
    status: meta.requestedFormats?.length > 0 ? "passed" : "warning",
    message: `Formats: ${(meta.requestedFormats || []).join(", ") || "none"}`,
    severity: "minor",
  });

  checks.push({
    name: "Model style",
    status: meta.style ? "passed" : "skipped",
    message: `Style: ${meta.style || "default"}`,
    severity: "info",
  });

  return checks;
}

function runPanoramaChecks(output: Partial<GeneratedOutput>): QualityCheckItem[] {
  const checks: QualityCheckItem[] = [];
  const meta = output.outputMetadata || {};

  checks.push({
    name: "Equirectangular format",
    status: meta.isEquirectangular ? "passed" : "failed",
    message: meta.isEquirectangular ? "Valid equirectangular format" : "Not equirectangular — will not render correctly in 360° viewer",
    severity: "critical",
  });

  checks.push({
    name: "Aspect ratio 2:1",
    status: meta.aspectRatio === "2:1" ? "passed" : "warning",
    message: `Ratio: ${meta.aspectRatio || "unknown"}`,
    severity: "major",
  });

  checks.push({
    name: "Hotspots defined",
    status: (meta.hotspots?.length || 0) > 0 ? "passed" : "skipped",
    message: `${meta.hotspots?.length || 0} hotspot(s) configured`,
    severity: "info",
  });

  return checks;
}

// ---------------------------------------------------------------------------
// Watermark Service
// ---------------------------------------------------------------------------

export function getWatermarkedUrl(originalUrl: string, watermarked: boolean): string {
  if (!watermarked || !originalUrl) return originalUrl;
  // In production, this would go through an image transformation service
  // that adds a "Sutra Studio — Preview" watermark overlay
  return `${originalUrl}${originalUrl.includes("?") ? "&" : "?"}watermark=sutra_preview&quality=60`;
}

export function shouldShowWatermark(output: Partial<GeneratedOutput>, isPaid: boolean): boolean {
  // Show watermark if:
  // 1. Not yet approved by admin
  // 2. Not yet paid by client
  if (output.status === "approved" && isPaid) return false;
  return true;
}

// ---------------------------------------------------------------------------
// Quality Gate Store
// ---------------------------------------------------------------------------

const QC_COLLECTION = "quality_checks";
const REVISION_COLLECTION = "revision_requests";

export class QualityGateStore {
  static async saveCheck(check: QualityCheck): Promise<void> {
    const db = adminDb();
    await db.collection(QC_COLLECTION).doc(check.id).set(check);
  }

  static async getChecksForOutput(outputId: string): Promise<QualityCheck[]> {
    const db = adminDb();
    const snap = await db
      .collection(QC_COLLECTION)
      .where("outputId", "==", outputId)
      .orderBy("performedAt", "desc")
      .get();
    if (!snap || !snap.docs) return [];
    return snap.docs.map((d: any) => d.data() as QualityCheck);
  }

  static async createRevisionRequest(request: RevisionRequest): Promise<RevisionRequest> {
    const db = adminDb();
    await db.collection(REVISION_COLLECTION).doc(request.id).set(request);
    return request;
  }

  static async getRevisionsByOrder(orderId: string): Promise<RevisionRequest[]> {
    const db = adminDb();
    const snap = await db
      .collection(REVISION_COLLECTION)
      .where("orderId", "==", orderId)
      .orderBy("createdAt", "desc")
      .get();
    if (!snap || !snap.docs) return [];
    return snap.docs.map((d: any) => d.data() as RevisionRequest);
  }

  static async updateRevisionStatus(
    revisionId: string,
    status: RevisionRequest["status"]
  ): Promise<void> {
    const db = adminDb();
    await db.collection(REVISION_COLLECTION).doc(revisionId).update({
      status,
      resolvedAt: status === "completed" || status === "declined" ? new Date().toISOString() : undefined,
    });
  }
}
